# -*- coding: utf-8 -*-
"""Source_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcAM7SILXy8AOQnWKJzvib_HXMB8hz9u

**Install required packages**
"""

!pip install lightkurve

!pip install altaipony

!pip install pandas

"""**TESS Response Function**"""

import scipy as sp
import math
import matplotlib.pyplot as plt
import numpy as np

pi = np.pi
h = 6.626e-27
c = 3.0e+10
k = 1.38e-16
boltzmann = 1.380622*(10**(-16))
stefbolt = 5.67*((10)**(-5))
rstar = 1.4442732*(10**(10))
Tflare = 9000
Teff = 3213

def planck(wav, T):
    a = 2.0*h*c**2
    b = h*c/(wav*k*T)
    intensity = a/ ( (wav**5)*(math.e**b - 1.0) )
    return intensity


x = np.array([[526,0],
[528,0],
[530,0],
[532,0],
[534,0.001],
[536,0.001],
[538,0.001],
[540,0.001],
[542,0.001],
[544,0.001],
[546,0.001],
[548,0.001],
[550,0.001],
[552,0.001],
[554,0.002],
[556,0.002],
[558,0.002],
[560,0.002],
[562,0.002],
[564,0.002],
[566,0.003],
[568,0.003],
[570,0.005],
[572,0.01],
[574,0.03],
[576,0.074],
[578,0.191],
[580,0.491],
[582,0.575],
[584,0.495],
[586,0.535],
[588,0.61],
[590,0.631],
[592,0.633],
[594,0.655],
[596,0.681],
[598,0.685],
[600,0.678],
[602,0.681],
[604,0.691],
[606,0.697],
[608,0.693],
[610,0.689],
[612,0.688],
[614,0.691],
[616,0.695],
[618,0.694],
[620,0.693],
[622,0.692],
[624,0.692],
[626,0.693],
[628,0.695],
[630,0.697],
[632,0.699],
[634,0.702],
[636,0.706],
[638,0.709],
[640,0.71],
[642,0.712],
[644,0.713],
[646,0.716],
[648,0.717],
[650,0.719],
[652,0.722],
[654,0.723],
[656,0.724],
[658,0.726],
[660,0.728],
[662,0.727],
[664,0.728],
[666,0.727],
[668,0.728],
[670,0.729],
[672,0.73],
[674,0.734],
[676,0.739],
[678,0.743],
[680,0.744],
[682,0.745],
[684,0.744],
[686,0.745],
[688,0.745],
[690,0.75],
[692,0.755],
[694,0.758],
[696,0.762],
[698,0.767],
[700,0.768],
[702,0.769],
[704,0.77],
[706,0.771],
[708,0.775],
[710,0.779],
[712,0.784],
[714,0.783],
[716,0.784],
[718,0.784],
[720,0.783],
[722,0.785],
[724,0.784],
[726,0.782],
[728,0.78],
[730,0.776],
[732,0.773],
[734,0.771],
[736,0.768],
[738,0.771],
[740,0.77],
[742,0.773],
[744,0.771],
[746,0.771],
[748,0.774],
[750,0.771],
[752,0.772],
[754,0.772],
[756,0.774],
[758,0.773],
[760,0.774],
[762,0.774],
[764,0.772],
[766,0.767],
[768,0.765],
[770,0.757],
[772,0.754],
[774,0.754],
[776,0.753],
[778,0.754],
[780,0.755],
[782,0.756],
[784,0.757],
[786,0.762],
[788,0.763],
[790,0.766],
[792,0.763],
[794,0.768],
[796,0.769],
[798,0.772],
[800,0.777],
[802,0.778],
[804,0.78],
[806,0.78],
[808,0.779],
[810,0.78],
[812,0.778],
[814,0.775],
[816,0.771],
[818,0.772],
[820,0.769],
[822,0.767],
[824,0.764],
[826,0.762],
[828,0.763],
[830,0.761],
[832,0.761],
[834,0.762],
[836,0.763],
[838,0.763],
[840,0.763],
[842,0.763],
[844,0.762],
[846,0.763],
[848,0.761],
[850,0.761],
[852,0.758],
[854,0.759],
[856,0.758],
[858,0.758],
[860,0.759],
[862,0.758],
[864,0.759],
[866,0.76],
[868,0.76],
[870,0.761],
[872,0.762],
[874,0.763],
[876,0.763],
[878,0.764],
[880,0.764],
[882,0.765],
[884,0.765],
[886,0.765],
[888,0.765],
[890,0.763],
[892,0.761],
[894,0.759],
[896,0.756],
[898,0.752],
[900,0.748],
[902,0.742],
[904,0.737],
[906,0.732],
[908,0.725],
[910,0.719],
[912,0.713],
[914,0.709],
[916,0.704],
[918,0.697],
[920,0.694],
[922,0.691],
[924,0.687],
[926,0.685],
[928,0.682],
[930,0.677],
[932,0.675],
[934,0.671],
[936,0.666],
[938,0.662],
[940,0.656],
[942,0.65],
[944,0.641],
[946,0.635],
[948,0.626],
[950,0.616],
[952,0.605],
[954,0.594],
[956,0.582],
[958,0.571],
[960,0.557],
[962,0.544],
[964,0.53],
[966,0.514],
[968,0.499],
[970,0.484],
[972,0.469],
[974,0.453],
[976,0.438],
[978,0.424],
[980,0.411],
[982,0.399],
[984,0.386],
[986,0.373],
[988,0.362],
[990,0.351],
[992,0.342],
[994,0.333],
[996,0.321],
[998,0.309],
[1000,0.299],
[1002,0.287],
[1004,0.276],
[1006,0.263],
[1008,0.252],
[1010,0.24],
[1012,0.227],
[1014,0.217],
[1016,0.205],
[1018,0.194],
[1020,0.184],
[1022,0.174],
[1024,0.164],
[1026,0.156],
[1028,0.147],
[1030,0.139],
[1032,0.132],
[1034,0.125],
[1036,0.117],
[1038,0.111],
[1040,0.104],
[1042,0.097],
[1044,0.09],
[1046,0.083],
[1048,0.077],
[1050,0.07],
[1052,0.063],
[1054,0.057],
[1056,0.051],
[1058,0.044],
[1060,0.038],
[1062,0],
[1064,0]])

x_list = x.tolist()
for ele in x_list:
    del ele[1]
wl=np.array(x_list)

x_list = x.tolist()
for ele in x_list:
    del ele[0]
rl=np.array(x_list)

Peff = planck(wl,Teff)
Pflare = planck(wl,Tflare)

#the integral part of the formula
resfunc_eff = np.multiply(Peff,rl)
resfunc_flare = np.multiply(Pflare,rl)
integral_part = sum(resfunc_eff)/sum(resfunc_flare)
print("value of the integral part = ", integral_part)

"""**Calculating the energy of the flares**"""

from altaipony.flarelc import FlareLightCurve
from altaipony.lcio import from_mast
from scipy.signal import find_peaks
from itertools import chain

from matplotlib import pyplot as plt
from astropy import units as u
import pandas as pd
import scipy as sp
import statistics as st

#Energydata = []
Peaktime_and_Energy_cadence120 = []

sect = [range(14,23), 24, 25, 40, 41, range(47,53), range(54,58), 60, range(73,81), range(82,85)]
flat = list(chain.from_iterable(x if hasattr(x, '__iter__') else [x] for x in sect))

for val in flat:
  flc = from_mast("TIC 233068870" , mode="LC", c=val, mission="TESS", cadence="short", author="SPOC")
  if flc is not None:
    dflc = flc.detrend("savgol")

    norm_de_flux = dflc.detrended_flux / np.nanmedian(dflc.detrended_flux)
    median = np.median(norm_de_flux)
    mad = sp.stats.median_abs_deviation(norm_de_flux)
    times = dflc.time.value
    timeandflux = np.column_stack((times, norm_de_flux))

    #print("normalised detrended flux points : ", norm_de_flux)
    #print("median of normalised detrended flux = ", median)
    #print("median absolute deviation = ", mad)
    #print("time = ", times)

    #timeandflux.shape
    #plt.plot(timeandflux[:,0], timeandflux[:,1])
    #plt.show()

    data = pd.DataFrame(timeandflux,columns=['time','flux'])
    #data = data.set_index('time')

    #data.loc[data.idxmax()]
    #data[data['flux']>median].plot()

    median = np.median(data['flux'])
    x = data['flux'].values
    peaks, _ = find_peaks(x, height= median + 5* mad)

    #peaktime = data['time'][peaks]

    #plt.plot(x)
    #plt.plot(peaks, x[peaks], "x")
    #plt.plot(np.zeros_like(x), "--", color="gray")
    #plt.show()
    #print(peaks)

    data['greater_than_median'] = data['flux']>median

    #data
    #data.head()

 #-------------------------------------------------------------------------------#

    data = data.reset_index()

    ### indexing
    peak_indices = peaks

    list_of_peaks = []

    ### extracting peaks
    def extract_peak(index):
      start_index = index
      end_index = index

      while start_index >= 0 and data['greater_than_median'][start_index]:
         start_index -= 1

      while end_index < len(data) and data['greater_than_median'][end_index]:
         end_index += 1

      if start_index != end_index and (end_index - start_index) >= 3:
         required_df = data[start_index+1:end_index]
         required_df['max_flux'] = required_df['flux'].max()
         required_df['peak_time'] = required_df['time'].loc[required_df['flux'] == required_df['flux'].max()]
         list_of_peaks.append(required_df)


    ### Iterate through the peak indices and extract peaks
    for index in peak_indices:
      extract_peak(index)

 #-------------------------------------------------------------------------------#

    concat_df = pd.concat(list_of_peaks)
    concat_df = concat_df.drop_duplicates(subset=['time'])

    list_of_unique_flares = []
    for max_flux in concat_df['max_flux'].unique():
      list_of_unique_flares.append(concat_df[concat_df['max_flux'] == max_flux])


    ### Calculation of Area and Luminosity of all Flare Points in each Flares
    list_of_sum_of_Lflares = []
    peaktime = []
    cadence = []

    for dataframe in list_of_unique_flares:
      dataframe['Aflare'] = pi * (rstar**2) * integral_part * (dataframe['flux'] - 1)
      dataframe['Lflare'] = stefbolt * ((Tflare)**4) * dataframe['Aflare']
      sum_of_Lflares = dataframe['Lflare'].sum()


      ### Pointing out Peak Time for each Flares
      peakt = dataframe['time'].loc[dataframe['flux'] == dataframe['flux'].max()]


      list_of_sum_of_Lflares.append(sum_of_Lflares)
      peaktime.append(peakt.values)


      ### Calculation of Cadence
      flare_duration = (dataframe['time'].max() - dataframe['time'].min()) * 86400
      no_of_flare_points = len(dataframe)
      caden = flare_duration / no_of_flare_points
      cadence.append(caden)


    array_of_sum_of_Lflares = np.array(list_of_sum_of_Lflares)
    array_of_peaktime = np.array([x[0] for x in peaktime])
    peaktime_and_sumofLflares = np.column_stack((array_of_peaktime,array_of_sum_of_Lflares))


    ### Calculation of Energy of the Flares
    list_of_Eflares = []


    list_of_Eflares = peaktime_and_sumofLflares[:,1] * cadence
    sector = int(val)*(np.ones(len(list_of_Eflares),dtype = int))
    peakandenergy = np.column_stack((peaktime_and_sumofLflares[:,0],list_of_Eflares,sector))
    Peaktime_and_Energy_cadence120.append(peakandenergy)

Peaktime_and_Energy_cadence120

"""**Downloading the data**"""

from google.colab import files
import numpy as np
import pandas as pd

if Peaktime_and_Energy_cadence120: # Check if the list is not empty
    all_peak_energy_data = np.concatenate(Peaktime_and_Energy_cadence120, axis=0)

    # Convert the numpy array to a pandas DataFrame
    df_peak_energy = pd.DataFrame(all_peak_energy_data, columns=['Peak Time', 'Energy', 'Sector'])

    # Save the DataFrame to a CSV file
    df_peak_energy.to_csv('Peaktime_and_Energy_cadence120.csv', index=False)

# Now you can download the file
files.download('Peaktime_and_Energy_cadence120.csv')